import { useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import { Close, Download } from './Icons'

/**
 * Reads a PDF in place, so a visitor can look at a piece without downloading
 * it. Written pieces are Word documents, which browsers cannot render — the
 * PDF previews are generated by `npm run docs:previews`.
 */
export default function DocumentPreview({ title, file, downloadFile, onClose }) {
  const closeRef = useRef(null)

  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onKey)

    const { overflow } = document.body.style
    document.body.style.overflow = 'hidden'
    closeRef.current?.focus()

    return () => {
      document.removeEventListener('keydown', onKey)
      document.body.style.overflow = overflow
    }
  }, [onClose])

  return createPortal(
    <div
      className="doc-viewer"
      role="dialog"
      aria-modal="true"
      aria-label={`Preview: ${title}`}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      <div className="doc-viewer__panel">
        <div className="doc-viewer__bar">
          <p className="doc-viewer__title">{title}</p>
          <div className="doc-viewer__actions">
            <a
              className="btn btn--ghost btn--small"
              href={file}
              target="_blank"
              rel="noopener noreferrer"
            >
              Open in new tab
            </a>
            {downloadFile && (
              <a
                className="btn btn--ghost btn--small"
                href={downloadFile}
                download
              >
                <Download width={15} height={15} />
                Download
              </a>
            )}
            <button
              type="button"
              ref={closeRef}
              className="icon-btn"
              onClick={onClose}
              aria-label="Close preview"
            >
              <Close />
            </button>
          </div>
        </div>

        <iframe
          className="doc-viewer__frame"
          src={`${file}#view=FitH`}
          title={`${title} — preview`}
        />

        <p className="doc-viewer__fallback">
          Cannot see the document?{' '}
          <a href={file} target="_blank" rel="noopener noreferrer">
            Open it in a new tab
          </a>
          .
        </p>
      </div>
    </div>,
    document.body,
  )
}
